[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
GO_IMPORT_PATH = "github.com/hsoJLeu/devoblog"

[context.production.environment]
HUGO_VERSION = "0.69.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

