[build]
publish = "public"  // default hugo build folder
command = "hugo" // hugo build command

[context.production.environment]
HUGO_VERSION = "0.69"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"